-- === Converted blit images for Blackjack Interface ===

playButtonBlit = {
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffff7777777777777777ffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ffff766666666666666666666666667777fffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ffff6444444444444444444444444666667ffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ffff644447f7343f34444f7447447746667ffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ffff34444f77f33f34443f743f34f744667ffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ffff4444473477373444777347337744667ffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ffff4444473473373444737343777744447ffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ffff3444473373373444737744347744444ffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ffff3444477734377733733743747744444ffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ffff3444477444377733743734777344444ffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ffff3444484444433844444844434444443ffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffff444444444444444444444444444447ffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ffffff777777777777777777777777777ffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
}

dealButtonBlit = {
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ffffffff74ccccccccccccccccccc47ffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ffffff7ccc4444444444444444444ccc7ffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffff3c4444444444444444444444444c3fffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ffff7cc4cc44c4cc4444cc4ccccccccccc7ffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ffff4ccccc3773447774c474c474cccccc4ffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fff7cccccc7f7f34f744c7f7c3f4ccccccc7fff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fff7cccccc7f4f74f7744f7f43f4ccccccc7fff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fff7cccccc7f4f74f7343f7f43f4ccccccc7fff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fff7cccccc7f7f74f7347f7f73f734ccccc7fff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ffff4ccccc3773c4777473c7747774cccc4ffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ffff7ccccccccccccccccccccccccccccc7ffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffff3ccccccccccccccccccccccccccc3fffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ffffff74ccccccccccccccccccccccc47ffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffff7344444444444444444444437fffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
}

rulesButtonBlit = {
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fff774444444444444444444444444444477fff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "f74ccccccccccccccccccccccccccccccccc47f"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "3ccc4444444444444444444444444444444ccc3"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "cc44444444444444444444444444444444444cc"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "c4444444444444444444444444444444444444c"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "4c444cc44c44cc44444cc44cc44c4444444c4c4"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ccc4c44444c4444444444cc4444444444cc4ccc"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ccccc3fff744f747f47f4cc7ffff43fff4ccccc"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ccccc7f77f74f747f47f4cc7f7334f74f7ccccc"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ccccc7f44f74f747f47f4cc7f3444ff444ccccc"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ccccc7f7ff44f747f47f4cc7fff7c7ff7cccccc"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ccccc7ffff44f747f47f4cc7f7774c3ff7ccccc"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ccccc7f43f74f747f47f4cc7f4cc4734f7ccccc"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ccccc7f44f74ff3ffc7f7747f7774f73f7ccccc"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ccccc7f44f7c3fff3c7fff73ffffc7fff4ccccc"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "cccccc4cccccc444ccc444cc444ccc44ccccccc"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ccccccccccccccccccccccccccccccccccccccc"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "ccccccccccccccccccccccccccccccccccccccc"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "cccccccccccccccccccccccccccccccccccccc4"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "344cccccccccccccccccccccccccccccccccc43"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "f7444ccccccccccccccccccccccccccccc4447f"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fff773444444444444444444444444444377fff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
    {"                                       ", "fffffffffffffffffffffffffffffffffffffff", "fffffffffffffffffffffffffffffffffffffff"},
}
